/**
 * GET /api/v1/projects/:id/report?format=md|json
 * 生成 PIA / Audit 等评估的完整报告，供外部 Agent 拉走做后续处理（发邮件/转飞书/转 docx 等）。
 */

import { db } from '@/lib/db';
import { verifyApiToken, requireScope } from '@/lib/api-auth';
import { errUnauthorized, errNotFound, errServer, ok } from '@/lib/api-response';
import { riskValue, riskLevelOf } from '@/lib/risk';
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(req: Request, { params }: { params: { id: string } }) {
  const ctx = await verifyApiToken(req.headers.get('authorization'));
  if (!ctx) return errUnauthorized();
  try { requireScope(ctx, 'GENERATE_REPORT'); } catch (e: any) { return errServer(e.message); }

  const url = new URL(req.url);
  const format = url.searchParams.get('format') || 'md';

  const project = await db.piaProject.findFirst({
    where: { id: params.id, organizationId: ctx.organizationId },
    include: {
      dataItems: true,
      scenarios: true,
      risks: { include: { mitigations: true } },
      conclusions: { orderBy: { createdAt: 'desc' }, take: 1 },
    },
  });
  if (!project) return errNotFound('评估项目');

  if (format === 'json') {
    return ok({
      ...project,
      scenarios: project.scenarios.map((s) => ({ ...s, annualVolume: s.annualVolume?.toString() ?? null })),
      risks: project.risks.map((r) => ({
        ...r,
        riskValue: r.likelihood * r.severity,
        riskLevel: riskLevelOf(r.likelihood * r.severity),
      })),
    });
  }

  const concl = project.conclusions[0];
  const md = `# ${project.title}

> ${project.code} · ${project.assessmentType} · ${project.version} · 评估期：${project.startedAt.toISOString().slice(0, 10)} → ${project.targetDoneAt?.toISOString().slice(0, 10) ?? '—'}

## 一、评估摘要

${concl?.overallVerdict ?? '尚未生成结论。'}

## 二、评估对象与范围

${project.scope}

## 三、评估目的

${project.purpose}

## 四、评估依据

${project.legalBases.map((l) => `- ${l}`).join('\n')}

## 五、信息项 / 控制项（${project.dataItems.length} 项）

| 编号 | 名称 | 分类 | 出境 | 现状 |
|------|------|------|------|------|
${project.dataItems.map((d) => `| ${d.code} | ${d.name} | ${d.classification} | ${d.isOutbound ? '✓' : ''} | ${d.status} |`).join('\n')}

## 六、场景 / 业务流程

${project.scenarios.map((s) => `### ${s.code} · ${s.name}\n\n${s.description}\n\n现状：${s.status} · 接收方：${s.receiverType}`).join('\n\n')}

## 七、风险摘要

${project.risks
  .map((r) => ({ ...r, value: riskValue(r.likelihood, r.severity) ?? 0 }))
  .sort((a, b) => b.value - a.value)
  .map((r) => `- **${r.code}** (${r.value} · ${riskLevelOf(r.value)}) — ${r.name}\n${r.mitigations.map((m) => `  - ↳ ${m.code} ${m.name}`).join('\n')}`)
  .join('\n')}

## 八、评估结论

${concl?.overallVerdict ?? '—'}

**给业务方的建议**：${concl?.businessAdvice ?? '—'}

**给监管的对外口径**：${concl?.regulatorTone ?? '—'}

## 九、复评机制

下次复评日期：${concl?.nextReviewAt?.toISOString().slice(0, 10) ?? '—'}

${project.reviewTriggers}

---

*Generated by PIA Forge · MIT License · https://github.com/juejiangxiaopianzi/pia-forge*
`;

  return new NextResponse(md, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${project.code}-${project.version}.md"`,
    },
  });
}
