import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { riskValue, riskLevelOf } from '@/lib/risk';

export async function GET(_: Request, { params }: { params: { id: string } }) {
  const project = await db.piaProject.findUnique({
    where: { id: params.id },
    include: {
      dataItems: true,
      scenarios: true,
      risks: { include: { mitigations: true } },
      conclusions: { orderBy: { createdAt: 'desc' }, take: 1 },
    },
  });
  if (!project) return NextResponse.json({ error: 'not found' }, { status: 404 });

  const concl = project.conclusions[0];

  const md = `# ${project.title}

> ${project.code} · ${project.version} · 评估期：${project.startedAt.toISOString().slice(0, 10)} → ${project.targetDoneAt?.toISOString().slice(0, 10) ?? '—'}

## 一、评估摘要

${concl?.overallVerdict ?? '尚未生成结论。'}

## 二、评估对象与范围

${project.scope}

## 三、评估目的

${project.purpose}

## 四、评估依据

${project.legalBases.map((l) => `- ${l}`).join('\n')}

## 五、信息项分类（${project.dataItems.length} 项）

| 编号 | 字段 | 分类 | 出境 | 现状 |
|------|------|------|------|------|
${project.dataItems.map((d) => `| ${d.code} | ${d.name} | ${d.classification} | ${d.isOutbound ? '✓' : ''} | ${d.status} |`).join('\n')}

## 六、出境场景

${project.scenarios.map((s) => `### ${s.code} · ${s.name}\n\n${s.description}\n\n现状：${s.status} · 接收方：${s.receiverType}`).join('\n\n')}

## 七、高风险摘要

${project.risks
  .map((r) => ({ ...r, value: riskValue(r.likelihood, r.severity) ?? 0 }))
  .filter((r) => riskLevelOf(r.value) === 'HIGH')
  .sort((a, b) => b.value - a.value)
  .map((r) => `- **${r.code}** (${r.value}) — ${r.name}\n${r.mitigations.map((m) => `  - ↳ ${m.code} ${m.name}`).join('\n')}`)
  .join('\n')}

## 八、评估结论

${concl?.overallVerdict ?? '—'}

**给业务方的建议**：${concl?.businessAdvice ?? '—'}

**给监管的对外口径**：${concl?.regulatorTone ?? '—'}

## 九、复评机制

下次复评日期：${concl?.nextReviewAt?.toISOString().slice(0, 10) ?? '—'}

${project.reviewTriggers}

---

*Generated by PIA Forge · MIT License · https://github.com/juejiangxiaopianzi/pia-forge*
`;

  return new NextResponse(md, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${project.code}-${project.version}.md"`,
    },
  });
}
